:PROPERTIES:
:ID:       2b468264-f8f7-4f76-a713-c7f8a495e261
:END:
#+title: 53-edo
* [[https://github.com/JeffreyBenjaminBrown/public_notes_with_github-navigable_links/blob/master/add_in_between_notes_to_mtv_monome.org#53-106][53-edo and 106-edo are fat-finger friendly.]]
* [[https://github.com/JeffreyBenjaminBrown/public_notes_with_github-navigable_links/blob/master/harmonic_theory_53_edo.org][Harmonic theory \ 53-edo]]
* TODO for Lumatone : [[https://github.com/JeffreyBenjaminBrown/public_notes_with_github-navigable_links/blob/master/7_53_x_3_53_r_x_ur_isomorphic_layout.org][7\53 x 3\53]]
** I mapped everything with the octave at 8,1 and 8,3.
** It's the only one with easy 5-limit triads.
* 53 5 12: 0-area 4x8, or 4x4 without 13
   , etrArea = 48
   , etrLayout =
       [ 0 steps; 1 % 1 ; string 0 ; fret 0
       , 53 steps; 2 % 1 ; string 4 ; fret 1
       , 31 steps; 3 % 2 ; string 3 ; fret - 1
       , 17 steps; 5 % 4 ; string 1 ; fret 1
       , 43 steps; 7 % 4 ; string 4 ; fret - 1
       , 9 steps; 9 % 8 ; string 2 ; fret - 3
       , 24 steps; 11 % 8 ; string 2 ; fret 0
       , 37 steps; 13 % 8 ; string 1 ; fret 5
       , 48 steps; 15 % 8 ; string 4 ; fret 0
* TODO for guitar
** TODO WINNER: [[https://github.com/JeffreyBenjaminBrown/public_notes_with_github-navigable_links/blob/master/17_53_x_3_53_isomorphic_note_layout.org][17\53 x 3\53]] is great!
** [[https://github.com/JeffreyBenjaminBrown/public_notes_with_github-navigable_links/blob/master/14_53_x_3_53_isomorphic_note_layout.org][14\53 x 3\53]] looks great!
** [[https://github.com/JeffreyBenjaminBrown/public_notes_with_github-navigable_links/blob/master/11_53_x_3_53_isomorphic_note_layout.org][11\53 x 3\53]] looks great!
** [[https://github.com/JeffreyBenjaminBrown/public_notes_with_github-navigable_links/blob/master/13_53_x_2_53_isomorphic_note_layout.org][13\53 x 2\53]]
   15 x 2 and even 17 x 2 also look pretty feasible, but harder.
* 8\53 x 1\53u: octave 7-3, width 6, well-behaved
  00 steps; 1  % 1; string 0; fret 0
  09 steps; 9  % 8; string 1; fret 1
  17 steps; 5  % 4; string 2; fret 1
  24 steps; 11 % 8; string 3; fret 0
  31 steps; 3  % 2; string 4; fret -1
  37 steps; 13 % 8; string 5; fret -3
  43 steps; 7  % 4; string 6; fret -5
  48 steps; 15 % 8; string 6; fret 0
  53 steps; 2  % 1; string 7; fret -3
* 11\53 x 2\53: 0-area 5x6, straight 2:3:9
      [  0 steps;  1 % 1 ; string 0 ; fret 0
      , 53 steps;  2 % 1 ; string 5 ; fret - 1
      , 31 steps;  3 % 2 ; string 3 ; fret - 1
      , 17 steps;  5 % 4 ; string 1 ; fret 3
      , 43 steps;  7 % 4 ; string 3 ; fret 5
      ,  9 steps;  9 % 8 ; string 1 ; fret - 1
      , 24 steps; 11 % 8 ; string 2 ; fret 1
      , 37 steps; 13 % 8 ; string 3 ; fret 2
* 10\53 x 3\53: 0-area 5x6, straight 2:5:7:13
      [  0 steps;  1 % 1 ; string 0 ; fret 0
      , 53 steps;  2 % 1 ; string 5 ; fret 1
      , 31 steps;  3 % 2 ; string 4 ; fret - 3
      , 17 steps;  5 % 4 ; string 2 ; fret - 1
      , 43 steps;  7 % 4 ; string 4 ; fret 1
      ,  9 steps;  9 % 8 ; string 0 ; fret 3
      , 24 steps; 11 % 8 ; string 3 ; fret - 2
      , 37 steps; 13 % 8 ; string 4 ; fret - 1
* 8\53r x 3\53dr : 53-edo Bosanquet
  00 steps; 01 % 1; string 0; fret 0
  53 steps; 02 % 1; string 5; fret 2
  31 steps; 03 % 2; string 3; fret 1
  17 steps; 05 % 4; string 1; fret 2
  43 steps; 07 % 4; string 3; fret 4
  09 steps; 09 % 8; string 1; fret 0
  24 steps; 11 % 8; string 0; fret 6
  37 steps; 13 % 8; string 1; fret 7
  48 steps; 15 % 8; string 4; fret 3
