:PROPERTIES:
:ID:       594672a6-5eec-4ba3-aa30-1298ecbe65bf
:END:
#+title: a paradise dependent on tacit knowledge
* see also
** [[https://github.com/JeffreyBenjaminBrown/public_notes_with_github-navigable_links/blob/master/we_know_more_than_we_can_tell_tacit_knowledge.org][tacit knowledge]]
** [[https://github.com/JeffreyBenjaminBrown/public_notes_with_github-navigable_links/blob/master/tacit_social_knowledge.org][tacit social knowledge]]
* the idea
I frequently imagine a kind of paradise that is paradise if only if you know how to appropriately interpret the experience, and if your unverifiable beliefs about others' interpretations are correct, and vice-versa.
* Maybe it is a fantasy based on a social extension of the Buddhist concept of Nirvana.
Nirvana supposedly feels good, not because anything has changed, but because you have changed how you see the world. That's got to be cool -- but it seems lonely. It seems even better for to change that perception as a group, with each member understanding the change they and the others had undergone.

Given that personal enlightenment is already famously ineffable. this social one would be even harder to eff.
* Is it scary?
It frightens me because tacit knowledge seems to be something one cannot be sure of. But maybe not. Perhaps shared experiences can verify the tacit knowledge many times over, without ever requiring it to be made explicit.
* I wish I could give examples.
Somehow, despite having imagined (seen?) it many times, when I try to provide specifics I am at a loss.
