:PROPERTIES:
:ID:       f3b1cc7c-1799-4a88-827c-1b81d5786109
:ROAM_ALIASES: "witness, bearing"
:END:
#+title: bearing witness
* There are certain truths I attend to and understand especially well, and report on fully when asked, yet (never?) volunteer.
* When asked I feel relief, validation, hpoe.
  that I am making a difference in some giant
  societal process I can't perceive
* the sense of an objective witness
:PROPERTIES:
:ID:       4b1d1674-df2a-4e9e-9906-cc874a63257f
:END:
  I and others are witnesses. Even AI might be conscious.
  But an objective witness would be something else.
  I don't believe in an anthropomorphic god,
    but the universe as a whole might be conscious.
    Indeed by containing consciousness one could argue that it is,
    tautologically, conscious -- it sees itself, feels itself, etc.
  But it is one thing to think those things,
    quite another to feel them.
* art
** Steps out of the wall, confirms happily, "Yes that happened to me."
   Blissfully over (as in past) himself most of the time.
** [[https://github.com/JeffreyBenjaminBrown/org_personal-ish_with-github-navigable_links/blob/master/fantasies_about_the_nature_of_power.org#long-after-your-reasonable-last-adventure-they-keep-reeling-you-back-in-such-is-waking-up-being-useful-in-gods-mind][Much later than your last adventure, they keep reeling you back in; such is waking up, being used in God's mind.]]
