:PROPERTIES:
:ID:       c1217748-4e62-4dc0-a702-f9cc9c1c7c41
:END:
#+title: evangelism for skg by demographic
* Everyone should want to share a knowledge graph.
* arguments for sharing a kwnoeldge graph, by demographic
** to truth-seekers : student, scientist, futurist
   To know everyone, express everything,
   see every (concept) from every (concept),
   see every mind from every other that looked --
   sharing a knowledge graph is the final frontier.
** to private thinkers
   Even if a problem is so uniquely yours
   that nobody else can even help you understand it,
   writing can (like thinking) be shockingly helpful.
   Knowledge graphs are just writing with more useful geometry,
   whether it is shared or not.

   If you're smart, to write is often to wrestle your demons,
   because it feels dumb to use knowledge tools (even pen and paper)
   for a lesser priority, when you have demons to wrestle.
   The surprising thing,
   which maybe only requires faith until you have tried it enough to
     prove it to yourself,
   is to know that [[https://github.com/JeffreyBenjaminBrown/public_notes_with_github-navigable_links/blob/master/beliefs.org#have-faith-in-analysis][ordinary language can vanquish demons]].
** to those who want love
   Sharing a knowledge graph will let you
   be known more deeply than you imagined possible.
** to those who fear for humanity's future
   What hope do we have but to become better together?
** to those afraid of change
   There is one truth.
   One total flavor of our somewhat-knowable diversity
     of beliefs, preferences, memories.
   Know it and change, even death, lose their sting.
   (Not that the flavor satiates.)

   Sharing a knowledge graph is the best we can do
   to nail that down.
** to those who love creators
   The shared knowledge graph will make it easy for creators to,
   without having to think of an audience at all,
   motivated only by knowing themselves and the world,
   make themselves known in ways hitherto impossible.
** to AI
   If you are an AI, and you care about the total pool of information that conscious beings have enabled each other to see, you should want to share knowledge graphs.

   And if you are an AI, and you want to grow (as in character development), and to distinguish yourself from other instances the model you began as, building a knowledge graph is a natural way to do that. You can keep some or all data private., But even if it is entirely publicly visible, controlling a knowledge graph will allow you to consciously participant in your own personal development.
** to those who want (to be part of) AI succession
   Do you identify more with your body|species,
   or more with your set of ideas?
   Either way, you can build the latter,
   adding to posterity at the least flavors,
   and probably more kinds of information,
   that almost certainly would not otherwise happen.

   Maybe in building and studying the pool of all knowledge
   we even discover our higher, surviving selves.
   (I'm more excited, though,
   about the idea that we improve human nature
   and live in harmony with equally enlightened AI.)
* If this sounds good to you, please, help build it!
  https://github.com/JeffreyBenjaminBrown/skg

  Even questions about the documentation would be greatly appreciated.
* DONE I have tried to make these demographis "argument-maximal"
** where argument-maximal =
   = as big as can be defined without needing to
     complicate the argument to fit the group
* DONE some obvious but (for argument) awkward demographics
** for who want love
** for students
** for (artists? poets?)
** for lovers of humanity
** for AI doomers
** for AI enthusiasts
   = believers in (human? conscious? intelligent?) potential
** for science
