:PROPERTIES:
:ID:       f5052dcf-20b5-48f7-85bb-478b16700b7a
:END:
#+title: stashed unused text
* data vs. metadata, and provenance queries
  In traditional data structures there is a sharp distinction between data and metadata. What an author said is data; who they are, when they said it, and who they cited are metadata. In the hypergraph database, there is no such distinction. As a result, it is easy to mix questions about provenance and questions about content in the same query.
* more things Shyg will enable
** the journal review process could be public
   Although it could still be done in private.
** emergent curricula
* I've worked on the idea for years.
Be forewarned: This is not an exciting story.

The idea started for me in maybe 2005. I stopped working in 2014 to work on something resembling it full-time. Before I had something I felt good about, I met Joshua Shinavier, whose Semantic Synchrony ("SmSn") dominated mine, so I joined him to work on that. SmSn is a beautiful personal knowledge graph system, but so complex that to my knowledge nobody but Josh uses it. (I used it myself for a few years, then switched to org-roam, which is less expressive but friendlier.)

After that I wrote Hode, an personal hypergraph knowledge base, rolling the database from scratch in Haskell. I also made a lot of noise about the effort online. The result was an application with a cool interface and a lousy database. Fortunately, TypeDB then came along and filled the database niche -- they offer a hypergraph database powerful enough to have seen some adoption in biotech and finance.

Outside of the database, the major innovation in Hode was its query language, [[https://github.com/JeffreyBenjaminBrown/public_notes_with_github-navigable_links/blob/master/shyg_long_essay_on.org#the-hash-query-language][Hash]], which I intend to use (with some extension) in Shyg.

The sharing and web-crawling aspects of Shyg are not something I have tried to code yet. (I have done some internet programming, though. After building a tax microsimulation of Colombia for the Observatorio Fiscal at Javeriana University, I put it online. I ran it on an AWS EC2 instance at Javeriana's expense so that anybody could visit and simulate the effects of tax proposals. Also I spent two years as the founding CTO of a tiny fintech startup running crypto arbitrage, in my spare time. We even made a profit, but not enough to justify the time commitment.)
