:PROPERTIES:
:ID:       4dbfdf07-f760-403d-9bcf-cddd14154fd1
:END:
#+title: types in Nu
* PITFALL: [[https://github.com/JeffreyBenjaminBrown/public-notes-in-org-roam-format/blob/master/in_nu_not_every_well_formed_expression_appears_to_have_a_type.org][Not every well-formed expression appears to have a type.]]
* to show an expression's type: use "describe"
  42 | describe
* to cast: use "into"
  "-5" | into int
* special number or number-adjacent data types
** date
*** convert date to table
    date now | date to-table
** duration
** range
*** closed [] ranges
    1..3
    includes both endpoints.
*** half-open [) ranges
    1..<5
    The reverse (] appears not to be available.
*** infinite
    0.. | take 5
** size (of file)
** binary
   > 0x[1F FF]  # Hexadecimal
   > 0b[1 1010] # Binary
   > 0o[777]    # Octal
* [[https://github.com/JeffreyBenjaminBrown/public-notes-in-org-roam-format/blob/master/strings_in_nu.org][strings in Nu]]
* durations permit math
  /home/jeffгЂ‰30day / 1sec                          10/12/2022 08:44:52 PM
  2592000
* collections
** "records" are product types
*** example
    /home/jeffгЂ‰echo {name: sam, rank: 10}            10/12/2022 09:46:40 PM
    в•­в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв•®
    в”‚ name в”‚ sam в”‚
    в”‚ rank в”‚ 10  в”‚
    в•°в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв•Ї
*** nested example
    /home/jeffгЂ‰echo {name: {a:1,b:2}, rank: 10}      10/12/2022 09:48:08 PM
    в•­в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв•®
    в”‚ name в”‚ {record 2 fields} в”‚
    в”‚ rank в”‚ 10                в”‚
    в•°в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв•Ї
*** retrieve a field
    {a:1} | get a
** lists
   [sam fred george]
** tables
*** can be input as a list titles plus a list of lists
    a list of column names + a list of rows (also lists).
    The semicolon and brackets below are important,
    but some of the whitespace could be a comma instead.

    > echo [[name1 name2];
            [1 2] [4 5]]
*** can be input as a list of (inhomogeneous!) records
    echo [ {name: sam, rank: 10},
           {name: bob, a:2, rank: 7} ]

    в•­в”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”¬в”Ђв”Ђв”Ђв”Ђв•®
    в”‚ # в”‚ name в”‚ rank в”‚ a  в”‚
    в”њв”Ђв”Ђв”Ђв”јв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”јв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”јв”Ђв”Ђв”Ђв”Ђв”¤
    в”‚ 0 в”‚ sam  в”‚   10 в”‚ вќЋ в”‚
    в”‚ 1 в”‚ bob  в”‚    7 в”‚  2 в”‚
    в•°в”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв”Ђв”Ђв”ґв”Ђв”Ђв”Ђв”Ђв•Ї
*** retrieve a column
    ps | get status
*** sort a table
    ls | sort-by size | reverse
*** filter a table
    ls | where size > 1kb
* column paths
** idea
   Tables can be ("inhomogeneous tensors"?).
   Column paths point to some linear subspace.
** example
   open data.toml | get foo.0.bar
                        ^^^^^^^^^
* [[https://github.com/JeffreyBenjaminBrown/public-notes-in-org-roam-format/blob/master/nu_code_blocks.org][Nu (code) blocks]]
* [[https://github.com/JeffreyBenjaminBrown/public-notes-in-org-roam-format/blob/master/nu_code_groups.org][Nu (code) groups]]
